# Invoke Shopify/shopify-cla-action
#
# This should be called on:
# - pull_request_target.{opened,synchronize}: for triggering from third party pulls
# - issue_comment.created: for detecting comments

name: Contributor License Agreement (CLA)

on:
  workflow_call:
    secrets:
      token:
        required: true
      cla-token:
        required: true

permissions: {}

jobs:
  cla:
    runs-on: ubuntu-latest
    if: |
      (github.event.issue.pull_request
        && !github.event.issue.pull_request.merged_at
        && contains(github.event.comment.body, 'signed')
      )
      || (github.event.pull_request && !github.event.pull_request.merged)
    permissions:
      pull-requests: write
    steps:
      - uses: Shopify/shopify-cla-action@1c5e9e39b803e4ed56c61a2f4bfd7a594c87c1f0 # v1.7.0
        with:
          github-token: ${{ secrets.token }}
          cla-token: ${{ secrets.cla-token }}
