# Automatically merge a Dependabot PR.
# Users must opt into merging upgrades by their ecosystem and semver gap.
# Accepting major upgrades implies accepting minor and patch. Accepting minor implies patch.
#
# This should be called on:
# - pull_request.{opened,reopened,synchronize}: ideally filtered to lockfile paths (e.g. go.sum, yarn.lock)

name: Dependabot auto-merge

on:
  workflow_call:
    inputs:
      all:
        required: false
        type: string
        default: none
        description: |
          Upgrades to automatically merge. Valid values are: all, none, major, minor, patch.

      # Prefer alphabetical, but "all" is special.
      actions:
        required: false
        type: string
        default: none
        description: |
          GitHub Actions upgrades to automatically merge. Valid values are: all, none, major, minor, patch.
      npm:
        required: false
        type: string
        default: none
        description: |
          NPM upgrades to automatically merge. Valid values are: all, none, major, minor, patch.

permissions: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Validate inputs
        run: |
          echo "all=${{ github.event.inputs.all }}"
          if [[ ! "${{ github.event.inputs.all }}" =~ ^(all|none|major|minor|patch)$ ]]; then
            echo "Invalid input: all=${{ github.event.inputs.all }}"
            exit 1
          fi

          echo "actions=${{ github.event.inputs.actions }}"
          if [[ ! "${{ github.event.inputs.actions }}" =~ ^(all|none|major|minor|patch)$ ]]; then
            echo "Invalid input: actions=${{ github.event.inputs.actions }}"
            exit 1
          fi

          echo "npm=${{ github.event.inputs.npm }}"
          if [[ ! "${{ github.event.inputs.npm }}" =~ ^(all|none|major|minor|patch)$ ]]; then
            echo "Invalid input: npm=${{ github.event.inputs.npm }}"
            exit 1
          fi

      - name: Retrieve Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@c9c4182bf1b97f5224aee3906fd373f6b61b4526 # v1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge GitHub Actions update
        if: |
          steps.metadata.outputs.package-ecosystem == 'github_actions' &&
          (
            (github.event.inputs.all == 'all' || github.event.inputs.actions == 'all') ||
            (
              steps.metadata.outputs.update-type == 'version-update:semver-major' &&
              (github.event.inputs.all == 'major' || github.event.inputs.actions == 'major')
            ) ||
            (
              steps.metadata.outputs.update-type == 'version-update:semver-minor' &&
              (
                (github.event.inputs.all == 'major' || github.event.inputs.actions == 'major') ||
                (github.event.inputs.all == 'minor' || github.event.inputs.actions == 'minor')
              )
            ) ||
            (
              steps.metadata.outputs.update-type == 'version-update:semver-patch' &&
              (github.event.inputs.all != 'none' || github.event.inputs.actions != 'none')
            )
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --merge "$PR_URL"

      - name: Merge NPM update
        if: |
          steps.metadata.outputs.package-ecosystem == 'npm_and_yarn' &&
          (
            (github.event.inputs.all == 'all' || github.event.inputs.npm == 'all') ||
            (
              steps.metadata.outputs.update-type == 'version-update:semver-major' &&
              (github.event.inputs.all == 'major' || github.event.inputs.npm == 'major')
            ) ||
            (
              steps.metadata.outputs.update-type == 'version-update:semver-minor' &&
              (
                (github.event.inputs.all == 'major' || github.event.inputs.npm == 'major') ||
                (github.event.inputs.all == 'minor' || github.event.inputs.npm == 'minor')
              )
            ) ||
            (
              steps.metadata.outputs.update-type == 'version-update:semver-patch' &&
              (github.event.inputs.all != 'none' || github.event.inputs.npm != 'none')
            )
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --merge "$PR_URL"
