# Publish an OpenSSF Scorecard
#
# This should be called on:
# - branch_protection_rule:
# - schedule: at least weekly (suggested)
# - push: to the default branch (optional)

name: Scorecard analysis workflow
on:
  workflow_call:
    secrets:
      token:
        required: true
        description: GitHub token. This can be secrets.GITHUB_TOKEN, or a fine-grained PAT granting read-only access.

permissions: {}

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    if: github.repository_visibility == 'public'
    permissions:
      contents: read
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{secrets.token}}
          publish_results: true
