name: Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 6'
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    permissions:
      contents: read
      id-token: write
    uses: Shopify/github-workflows/.github/workflows/scorecard.yaml@main
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}
