# Publish an OpenSSF Scorecard
#
# This should be called on:
# - branch_protection_rule:
# - schedule: at least weekly (suggested)
# - push: to the default branch (optional)

name: Scorecard analysis workflow
on:
  workflow_call:
    secrets:
      token:
        required: true
        description: GitHub token. This can be secrets.GITHUB_TOKEN, or a fine-grained PAT granting read-only access.

permissions: {}

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    if: github.repository_visibility == 'public'
    permissions:
      contents: read
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{secrets.token}}
          publish_results: true
