# Publish an OpenSSF Scorecard
#
# This should be called on:
# - branch_protection_rule:
# - schedule: at least weekly (suggested)
# - push: to the default branch (optional)

name: Scorecard analysis workflow
on:
  workflow_call:
    secrets:
      token:
        required: true
        description: GitHub token. This can be secrets.GITHUB_TOKEN, or a fine-grained PAT granting read-only access.

permissions: {}

jobs:
  analysis:
    name: Scorecard analysis
    # Shopify tends to use another runner pool, but ScoreCard's API trusts GitHub runners more.
    runs-on: ubuntu-latest
    if: github.repository_visibility == 'public'
    permissions:
      contents: read
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031 # v2.2.0
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{secrets.token}}
          publish_results: true
